{
  "jobs": {
    "check": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v5"
        },
        {
          "uses": "nixbuild/nix-quick-install-action@master",
          "with": {
            "nix_conf": "keep-env-derivations = true\nkeep-outputs = true\n"
          }
        },
        {
          "uses": "nix-community/cache-nix-action@main",
          "with": {
            "primary-key": "a-single-key"
          }
        },
        {
          "run": "nix flake -vv --print-build-logs --accept-flake-config check"
        }
      ]
    }
  },
  "on": {
    "push": {},
    "workflow_call": {}
  }
}
